### ISSUE TITLE
Error Sending new messages from the Results page

### ISSUE THREAD

**Issue by SyntaxStacks** [kirpeep/Kirpeep#11]
ActiveRecord::RecordNotFound in MessagesController#create

Couldn't find Message with id=start

**Comment by SyntaxStacks** [comment]
this has been resolved but now they need to be marked as unread when opened

**Comment by kyleondata** [comment]
Can we close this out?  Is it still an issue.  Seems like messages work mostly now.

**Comment by kirpeep** [comment]
yeah, the message can be sent from the result page so I'm good with this, I'll be working on the wonky behaviors of the replies
