### ISSUE TITLE
Exchanges without messages throw the following error

### ISSUE THREAD

**Issue by SyntaxStacks** [kirpeep/Kirpeep#12]
NoMethodError in Exchanges#show

Showing /var/www/KirpeepTest/app/views/shared/_initiated_exchange.html.erb where line #95 raised:

undefined method `message_id' for nil:NilClass
Extracted source (around line #95):

92:             <span>Message</span>
93:             <div class="rounded-map shadow" id="message" style="overflow:scroll; height: 100px;">
94:                 <% exch_message_link = ExchangeMessageLink.where(:exchange_id => @exch.id).first %>
95:                 <% current_message = Message.find(exch_message_link.message_id) %>
96:                 <% reply_message_id = current_message.id %>
97:                 <% begin %>
98:                     <%= render :partial =>current_message, :locals => {:current_message => current_message} %>

**Comment by kyleondata** [comment]
Fixed by @TheGigaRaptor
