### ISSUE TITLE
Editting on Profile text boxes not accepting new values

### ISSUE THREAD

**Issue by stevenaq** [kirpeep/Kirpeep#122]
It is possible to edit your profile by going to the drop down and edit profile option. However, when clicking directly on the text fields when viewing your own profile you are not allowed to save the info that you've entered. You can click on the area and type information, it just doesn't get viewed(not sure if it is storing it though). I clicked enter on my keyboard when I was done typing.

**Comment by kyleondata** [comment]
Fixed
