### ISSUE TITLE
Initiated exchange

### ISSUE THREAD

**Issue by kirpeep** [kirpeep/Kirpeep#23]
Add the ability to add multiple items

**Comment by kirpeep** [comment]
Implement CRUD features

**Comment by kirpeep** [comment]
I made it through an exchange last night but there are still some issues with the actual listings. Ex. I went for a high five, but got web development, cool, but not what i needed

**Comment by SyntaxStacks** [comment]
I've fixed a majority of the init issues, now working on kirpoints and listings on the fly

**Comment by kyleondata** [comment]
done
