### ISSUE TITLE
Kirpoints

### ISSUE THREAD

**Issue by kirpeep** [kirpeep/Kirpeep#25]
Security
Buy page
how the currency is pegged against currency in circulation

**Comment by kyleondata** [comment]
I will take this one.

**Comment by kyleondata** [comment]
Also something to think about. We need to hack the listings so you have the option of specifying how many Kirpoints you would accept in the exchange for the listing

**Comment by kirpeep** [comment]
I agree. Kps started off as simple sale.

**Comment by kyleondata** [comment]
For this we will need to get a paypal account started if we have not already done so.  

Once we have that we can start to setup the quick checkout process for buying kirpoints. 

Here is an article that goes more indepth

https://www.x.com/developers/paypal/products/express-checkout

**Comment by kirpeep** [comment]
Let me know what we need for it, and I will compile the information to get
this set up.

**Comment by kyleondata** [comment]
Here is some info from their site...  Not sure what the details of the upgrade are

How to get started

```
Check your account status. Login to PayPal. 
Go to your PayPal Profile and click My settings. 
Confirm that your “Account Type” is either Premier or Business, or upgrade your account.
Check your API settings. 
Click My selling tools.
Expand “Selling online” if needed and check “API access.”
Click Update and Add or edit API permission or View API signature.
Test your integration using the PayPal Sandbox. (Registration is free.)
```

Once you’ve verified that your implementation works correctly in the Sandbox, you’re now ready to go live.

See also Express Checkout API Getting Started Guide

**Comment by kyleondata** [comment]
Got the add kirpoints working (without paypal), add kirpoints to listings, show balance.  Only thing now is to incorp kirpoints to the exchange and round out paypal.

I will need to get the info on the paypal stuffs from Steven.

**Comment by kirpeep** [comment]
I'll have that set up shortly. Just got to John's.

SQ

**Comment by kyleondata** [comment]
you can now buy kirpoints from paypals test site.

**Comment by kirpeep** [comment]
NICE!

SQ

**Comment by kyleondata** [comment]
The only thing left for this bug is to integrate kirpoints as an exchangeable item.

**Comment by kyleondata** [comment]
done and done!
