### ISSUE TITLE
Account creation does not allow periods on the front of the email

### ISSUE THREAD

**Issue by kyleondata** [kirpeep/Kirpeep#33]
This is an issue with the regular expression validator.

**Comment by kyleondata** [comment]
@TheGigaRaptor - what was the file that did the . to (dot) manipulation?

I believe it is some JavaScript file.

**Comment by SyntaxStacks** [comment]
Assets/Javascripts/index.js.erb

Sent from Samsung Galaxy Note on T-mobile. America's First Nationwide 4G NetworkKyle Jennings notifications@github.com wrote:@TheGigaRaptor - what was the file that did the . to (dot) manipulation?

I believe it is some JavaScript file.

**Comment by kyleondata** [comment]
@TheGigaRaptor fixed this!
