### ISSUE TITLE
Capture search queries with user id

### ISSUE THREAD

**Issue by kirpeep** [kirpeep/Kirpeep#48]

**Comment by kyleondata** [comment]
is this really a launch specific task?

**Comment by SyntaxStacks** [comment]
I don't believe so, it's from Steven

Sent from Samsung Galaxy Note on T-mobile. America's First Nationwide 4G NetworkKyle Jennings notifications@github.com wrote:is this really a launch specific task?

**Comment by kyleondata** [comment]
Done
