### ISSUE TITLE
Kirpoints not correctly displaying 

### ISSUE THREAD

**Issue by stevenaq** [kirpeep/Kirpeep#56]
I bout 15, money transferred, but my count is still 0.  However, it does show the transaction in my transactions.

**Comment by kyleondata** [comment]
there was an error occurring.  Do you still have it?

**Comment by stevenaq** [comment]
No. Because we don't have any of the data. But I should start with 15
kirpoints.

**Comment by kyleondata** [comment]
there was a bug when it tried to increment the kirpoints. fixed now however if you had the problem before the amount needs to be added manually.
