### ISSUE TITLE
Multi-item exchanges

### ISSUE THREAD

**Issue by kirpeep** [kirpeep/Kirpeep#6]
This is something that I'm currently working on (10/05/12)

This is the ability for users to exchange multiple items with another user in an exchange
also this includes the functionality to add listings on the fly during the exchange

**Comment by kyleondata** [comment]
Am I suppose to be assigned this?

**Comment by SyntaxStacks** [comment]
yes, muhahahaahah

**Comment by kyleondata** [comment]
Lets have a meeting on this one.

**Comment by kyleondata** [comment]
Is this closed on my end?  As far as helping out with setting up the ajax request help you needed?  Or is there still some stuff I need to do?

**Comment by SyntaxStacks** [comment]
It's all good IM working on it now

Sent from Samsung Galaxy Note on T-mobile. America's First Nationwide 4G NetworkKyle Jennings notifications@github.com wrote:Is this closed on my end? As far as helping out with setting up the ajax request help you needed? Or is there still some stuff I need to do?

**Comment by kyleondata** [comment]
Should I assign it to you then?

**Comment by kirpeep** [comment]
yeah and its actually done, kinda tied in to initiate exchange, but I'll close that issue after I work out the bugs mentioned in that issue
