### ISSUE TITLE
verification link points to signup.kirpeep.com

### ISSUE THREAD

**Issue by stevenaq** [kirpeep/Kirpeep#72]
So I can't verify.

**Comment by kyleondata** [comment]
Are you talking about the activate account email?  If so I can not replicate this issue.  Can you confirm it wasn't a one time fluke.  

Thanks.

**Comment by kyleondata** [comment]
Is this still an issue?

**Comment by stevenaq** [comment]
Not this last time it wasn't.

**Comment by kyleondata** [comment]
Ok, I am closing this then! :)
