### ISSUE TITLE
Beautification

### ISSUE THREAD

**Issue by kirpeep** [kirpeep/Kirpeep#9]
Overall design of the site needs to be polished, Sara will help us with the design

**Comment by kyleondata** [comment]
I would love to get some specifics on this. It should probably be broken into smaller groups or even individual items so we can track progress better.

Thoughts?

**Comment by kirpeep** [comment]
I agree, I rushed to get it all up this morning. I'll work on ironing it out so it includes the specifics

Sent from Samsung Galaxy Note on T-mobile. America's First Nationwide 4G NetworkKyle Jennings notifications@github.com wrote:I would love to get some specifics on this. It should probably be broken into smaller groups or even individual items so we can track progress better.

**Comment by kyleondata** [comment]
Is this done?  I feel like there may be a few items left here and there but does it warrant having a bug open for minor UI tweaks? Do we want to wait to talk to Sara before closing?  I just know she is busy and don't want to delay the milestone if she is unavailable at the moment.

**Comment by kyleondata** [comment]
Closing this out.

**Comment by kirpeep** [comment]
Agreed

**Comment by kirpeep** [comment]
I already sent you my thoughts. I'll re-send.

On Thu, Oct 25, 2012 at 8:30 AM, Kyle Jennings notifications@github.comwrote:

> Closing this out.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kirpeep/Kirpeep/issues/9#issuecomment-9777457.

## 

Sara Moffett
Kirpeep, Inc.
Design and Database Deviant
210.201.2373
sara@kirpeep.com
http://www.kirpeep.com
